name: Setup Apama

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:    
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false

      matrix:
        include:
          - run-id: amd64_linux
            os: ubuntu-latest
            apama-version: 10.5.3.2
            
          - run-id: amd64_win
            os: windows-latest
            apama-version: 10.5.3.2

          - run-id: amd64_linux
            os: ubuntu-latest
            apama-version: 10.1.0.5
            
          - run-id: amd64_win
            os: windows-latest
            apama-version: 10.1.0.5

          - run-id: amd64_linux_oldest
            os: ubuntu-latest
            apama-version: 9.10.0.3
            
          - run-id: amd64_win_oldest
            os: windows-latest
            apama-version: 9.10.0.3

    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v2

      - name: Cached Apama installation
        # always-upload is a fork of actions/cache allows cache to be saved even if some later steps (e.g. testing) fail
        uses: pat-s/always-upload-cache@v2.1.3

        id: cache-apama-installer
        with:
            path: ~/cached-apama-installation.tar
            # To use a clean cache, update the number at the end of this key
            key: apama-${{ runner.os }}-${{ matrix.apama-version }}-cache1

      - uses: ./
        with:
          # The 4-digit version to download from http://www.apamacommunity.com/downloads/
          apama-version: ${{ matrix.apama-version }}

      - name: Test starting the Apama correlator
        # Basic test that should work on all Apama versions
        shell: bash
        run: |
          env | sort

          correlator --version

      - name: Test the rest of the Apama environment
        shell: bash
        # Some tools aren't in the oldest version
        if: matrix.apama-version != '9.10.0.3'
        run: |
          engine_deploy -h
          
          $APAMA_PYSYS makeproject --help
          
          which javac
          javac -version
          
          which python
          python --version
          
          which ant
          ant -version
          
