name: Setup Apama

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:    
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false

      matrix:
        include:
          - run-id: amd64_linux
            os: ubuntu-latest
            
          - run-id: amd64_win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v2

      - name: Cached Apama installation
        # always-upload is a fork of actions/cache allows cache to be saved even if some later steps (e.g. testing) fail
        uses: pat-s/always-upload-cache@v2.1.3

        id: cache-apama-installer
        with:
            path: ~/cached-apama-installation.tar
            # To use a clean cache, add extra chars to this key
            key: apama-${{ runner.os }}-10.5.3.2-TODO2

      - uses: ./
        with:
          apama-version: 10.5.3.2

      - name: Test the installation
        shell: bash
        run: |
          correlator --version
          engine_deploy -h
          
          $APAMA_PYSYS run --help
          
          which javac
          javac --version
          
          which python
          python --version
          
          which ant
          ant --version
          
          env | sort
        